# Generated by Django 5.0.2 on 2025-01-03 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_docaccess_doc_alter_docaccess_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docaccess',
            unique_together={('doc', 'user')},
        ),
    ]
